#!/usr/bin/env bash
set -eo pipefail
IFS=$'\n\t'

CLI=$(basename "${BASH_SOURCE[0]}")
VERSION=v0.0.0

# Set default values for options
repo=static
dry_run=false
message="Updated at: \`$(date +%Y-%m-%d\ %H:%M:%S)\`"
owner=$(gh config get -h github.com user)
branch=$(gh api repos/$owner/$repo --jq .default_branch)

usage() {
    cat <<-EOF
Usage: $CLI <repo> <...paths> or $CLI <url>

> Upload folders or files to GitHub \`static\` repo

Arguments:
    <...paths>           folders or files path

Options:
    -h                   output usage
    -v                   output version
    -d                   dry-run mode, only output the command
    -m                   commit message. Default is \`Updated at: <datetime>\`
    -r                   repository name, <owner/repo>. Default is \`<username>/static\`

Examples:
    gh upload README.md
    gh upload LICENSE
EOF
    exit
}

version() {
    echo "$CLI $VERSION"
    exit
}

# Parse options
while getopts ":h:v:d:m:r" opt; do
    case ${opt} in
    h)
        usage
        ;;
    v)
        version
        ;;
    d)
        dry_run=true
        ;;
    m)
        message=$OPTARG
        ;;
    r)
        tmp=$OPTARG
        # If containts '/'
        if [[ tmp =~ / ]]; then
            owner=${tmp%/*}
            repo=${tmp#*/}
        else
            repo=$tmp
        fi
        ;;
    \?)
        usage
        ;;
    esac
done
shift $((OPTIND - 1))

# Main
if [[ $# -eq 0 ]]; then
    usage
fi
# Create blobs
files=()
blobs=()
for file in "$@"; do
    sha=$(gh api /repos/$owner/$repo/git/blobs -f "encoding=base64" -f "content=$(base64 $file)" | jq -r '.sha')
    blobs+=($sha)
    files+=($file)
done

# Parent sha
parent_sha=$(gh api /repos/$owner/$repo/branches/$branch | jq -r '.commit.sha')
# Create tree
command="gh api -X POST /repos/$owner/$repo/git/trees -f \"base_tree=$parent_sha\""
for ((i = 0; i < $#; i++)); do
    file=${files[$i]}
    sha=${blobs[$i]}
    command+=" -f \"tree[][path]=$file\" -f \"tree[][mode]=100644\" -f \"tree[][type]=blob\" -f \"tree[][sha]=$sha\""
done
command+=" | jq -r '.sha'"
tree_sha=$(eval $command)

# Post commit
commit_sha=$(
    gh api -X POST /repos/$owner/$repo/git/commits -f "tree=${tree_sha}" -f "parents[]=${parent_sha}" \
        -f "message=$message" | jq -r '.sha'
)
# Update ref
_=$(gh api -X PATCH /repos/$owner/$repo/git/refs/heads/$branch -f "sha=$commit_sha")

# TODO:
echo "Update Success"
